/**
 * The sample database the SQL workbench runs against.
 *
 * Every SQL run boots a fresh in-memory SQLite (sql.js) and replays this
 * script, so a query is reproducible and nothing a candidate types can leak
 * into the next attempt.
 *
 * Three rules kept the data honest:
 *   1. Dates are relative to `now`, generated by SQLite's own date functions —
 *      otherwise "revenue over the last 30 days" would return nothing a month
 *      after this file was written. Nothing is dated in the future.
 *   2. The messy parts are deliberate, because they're what SQL rounds probe:
 *      NULL amounts and emails, still-open sessions with a NULL `ended_at`,
 *      duplicated event rows from an at-least-once pipeline, days with no
 *      orders at all (so gap-filling matters), overlapping sessions, a real
 *      revenue tie, and a long right tail on order value (so the mean lies).
 *   3. **Every SQL question in `loops.ts` must have data behind it.** Each
 *      block below says which question it feeds; the funnel needs an
 *      `activated` event and a first purchase near signup, retention needs
 *      cohorts big enough to average, "median per segment" needs a segment,
 *      NRR needs upgrades, downgrades and churn across several months.
 *      Adding a question that needs new shapes means adding the rows too.
 */

export interface SqlFixtureTable {
  name: string;
  columns: string;
  /** What's interesting/awkward about this table — shown next to the schema. */
  note: string;
}

export const SQL_FIXTURE_TABLES: SqlFixtureTable[] = [
  {
    name: "users",
    columns: "id, name, email, country, segment, signup_date",
    note:
      "122 users signed up over the last ~6 months (≈5 per week, so cohorts have mass). country is US | GB | DE | CA, segment is smb | mid_market | enterprise. Some emails are NULL.",
  },
  {
    name: "orders",
    columns: "id, user_id, created_at, amount, status",
    note:
      "~1,000 orders: dense over the last 59 days, sparser back to ~6 months, plus a first purchase 1-12 days after signup for most users. status is paid | cancelled | refunded, ~3% of amounts are NULL, some days have none, and a few enterprise deals are 50x a normal order.",
  },
  {
    name: "events",
    columns: "event_id, user_id, event_name, ts, ingested_at",
    note:
      "event_name is one of signup | activated | view_dashboard | create_project | invite_teammate | checkout. ~70% of users ever activate. ~5% of rows are redelivered: same event_id, later ingested_at.",
  },
  {
    name: "sessions",
    columns: "user_id, started_at, ended_at",
    note:
      "~780 sessions over the last 30 days. A few are still open (ended_at IS NULL) and some overlap for the same user.",
  },
  {
    name: "subscriptions",
    columns: "user_id, plan, started_at, ended_at",
    note:
      "One row per plan a user has been on, starting at signup. ended_at IS NULL means still paying; some churned for good, some came back on a bigger plan and some on a smaller one.",
  },
  {
    name: "plans",
    columns: "name, monthly_price",
    note: "free 0, pro 25, team 80, enterprise 400; join here for revenue.",
  },
];

/** Compact schema listing, for starter templates and grading prompts. */
export const SQL_SCHEMA_SUMMARY = SQL_FIXTURE_TABLES.map(
  (t) => `${t.name}(${t.columns})`
).join("\n");

/** The same listing with the gotchas attached — used in AI prompts. */
export const SQL_SCHEMA_BRIEF = SQL_FIXTURE_TABLES.map(
  (t) => `- ${t.name}(${t.columns}): ${t.note}`
).join("\n");

/**
 * DDL + seed data. Deterministic: recursive CTEs with modular arithmetic
 * instead of random(), so two runs return the same rows.
 *
 * SQLite gotcha: `||` binds tighter than `%`, so every modulo inside a string
 * concat is fully parenthesized. `'-' || (n*3) % 59 || ' days'` is NULL.
 */
export const SQL_FIXTURE_SQL = `
CREATE TABLE users (
  id INTEGER PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT,
  country TEXT NOT NULL,
  segment TEXT NOT NULL,
  signup_date TEXT NOT NULL
);

-- 120 users over ~6 months. Signup spread matters twice over: weekly cohorts
-- need ~5 users before a retention percentage means anything, and segment is
-- keyed off a modulus coprime with country so enterprise isn't all one country.
INSERT INTO users (id, name, email, country, segment, signup_date)
WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 120)
SELECT
  n,
  'User ' || n,
  CASE WHEN n % 13 = 0 THEN NULL ELSE 'user' || n || '@example.com' END,
  CASE n % 5 WHEN 0 THEN 'US' WHEN 1 THEN 'US' WHEN 2 THEN 'GB' WHEN 3 THEN 'DE' ELSE 'CA' END,
  CASE WHEN n % 7 = 0 THEN 'enterprise' WHEN n % 3 = 0 THEN 'mid_market' ELSE 'smb' END,
  date('now', '-' || (5 + (n * 3) % 175) || ' days')
FROM seq;

-- Two accounts that exist to tie. Same country, same revenue, one order each:
-- "top 3 per country" has to decide between RANK, DENSE_RANK and ROW_NUMBER,
-- and a tie at the top is where that choice shows.
INSERT INTO users (id, name, email, country, segment, signup_date) VALUES
  (121, 'User 121', 'user121@example.com', 'GB', 'enterprise', date('now', '-140 days')),
  (122, 'User 122', 'user122@example.com', 'GB', 'enterprise', date('now', '-138 days'));

CREATE TABLE orders (
  id INTEGER PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id),
  created_at TEXT NOT NULL,
  amount REAL,
  status TEXT NOT NULL
);

-- The dense recent window: what a "last 30 days" question reads.
INSERT INTO orders (id, user_id, created_at, amount, status)
WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 900)
SELECT
  n,
  1 + (n * 7) % 120,
  datetime('now', '-' || ((n * 3) % 59) || ' days', '-' || ((n * 11) % 24) || ' hours'),
  CASE WHEN n % 29 = 0 THEN NULL ELSE ROUND(9.5 + ((n * 37) % 380) / 4.0, 2) END,
  CASE WHEN n % 17 = 0 THEN 'cancelled' WHEN n % 23 = 0 THEN 'refunded' ELSE 'paid' END
FROM seq;

-- Older history, 60-180 days back, so cohort and funnel questions work for the
-- users who signed up months ago instead of returning nothing.
INSERT INTO orders (id, user_id, created_at, amount, status)
WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 320)
SELECT
  2000 + n,
  1 + (n * 11) % 120,
  datetime('now', '-' || (60 + (n * 7) % 120) || ' days', '-' || ((n * 5) % 24) || ' hours'),
  ROUND(12 + ((n * 23) % 300) / 3.0, 2),
  CASE WHEN n % 19 = 0 THEN 'refunded' ELSE 'paid' END
FROM seq
-- Nobody buys before they sign up.
WHERE datetime('now', '-' || (60 + (n * 7) % 120) || ' days')
      >= (SELECT signup_date FROM users WHERE id = 1 + (n * 11) % 120);

-- First purchase, 1-12 days after signup for ~60% of users. The funnel question
-- attributes it "within 7 days", so some of these land deliberately outside the
-- window and the window has to do work.
INSERT INTO orders (id, user_id, created_at, amount, status)
SELECT
  4000 + u.id,
  u.id,
  datetime(u.signup_date, '+' || (1 + (u.id * 5) % 12) || ' days', '+' || (3 + (u.id * 7) % 15) || ' hours'),
  ROUND(19 + ((u.id * 13) % 210) / 2.0, 2),
  'paid'
FROM users u
WHERE (u.id * 7) % 10 < 6
  AND u.id <= 120
  AND datetime(u.signup_date, '+' || (1 + (u.id * 5) % 12) || ' days', '+' || (3 + (u.id * 7) % 15) || ' hours')
      <= datetime('now');

-- A long right tail: a handful of enterprise deals worth 50x a normal order, so
-- the mean order value is a lie and the median is the honest number.
INSERT INTO orders (id, user_id, created_at, amount, status)
SELECT
  5000 + u.id,
  u.id,
  datetime('now', '-' || (2 + (u.id * 3) % 40) || ' days', '-' || ((u.id * 5) % 20) || ' hours'),
  ROUND(1800 + (u.id * 137) % 7000, 2),
  'paid'
FROM users u
WHERE u.segment = 'enterprise' AND u.id <= 120;

-- The tie: one order each, identical amount, and no other orders (every batch
-- above is capped at id 120). The day offsets avoid the emptied days below —
-- including the day either side, since a small hour offset can roll the date
-- over — so the DELETE can't take one side of the tie and leave the other.
INSERT INTO orders (id, user_id, created_at, amount, status) VALUES
  (6001, 121, datetime('now', '-21 days', '-3 hours'), 15400.00, 'paid'),
  (6002, 122, datetime('now', '-24 days', '-6 hours'), 15400.00, 'paid');

-- Leave a few days with no orders at all, so a daily-revenue query has to
-- decide whether to fill the gaps. Done as a DELETE at the end because four
-- separate inserts land in this window and any one of them would fill a gap.
DELETE FROM orders
WHERE CAST(julianday(date('now')) - julianday(date(created_at)) AS INTEGER)
      IN (4, 5, 18, 33, 47);

CREATE INDEX orders_created_at ON orders (created_at);
CREATE INDEX orders_user_id ON orders (user_id);

CREATE TABLE events (
  -- The producer's id. NOT unique here: a redelivered event keeps its id and
  -- arrives again with a later ingested_at, which is what makes "what's your
  -- dedup key?" a real question.
  event_id TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  event_name TEXT NOT NULL,
  ts TEXT NOT NULL,
  ingested_at TEXT NOT NULL
);

INSERT INTO events (event_id, user_id, event_name, ts, ingested_at)
SELECT
  'evt_signup_' || id,
  id,
  'signup',
  datetime(signup_date, '+' || ((id * 5) % 12) || ' hours'),
  datetime(signup_date, '+' || ((id * 5) % 12) || ' hours', '+' || (2 + id % 40) || ' seconds')
FROM users;

-- Funnel step 2. ~70% of users ever activate, 1-5 days in, so signup →
-- activation → first purchase drops off at every step instead of being 100%.
INSERT INTO events (event_id, user_id, event_name, ts, ingested_at)
SELECT
  'evt_activated_' || id,
  id,
  'activated',
  datetime(signup_date, '+' || (1 + (id * 7) % 5) || ' days', '+' || (3 + (id * 3) % 10) || ' hours'),
  datetime(signup_date, '+' || (1 + (id * 7) % 5) || ' days', '+' || (3 + (id * 3) % 10) || ' hours', '+' || (3 + id % 25) || ' seconds')
FROM users
WHERE (id * 3) % 10 < 7
  AND datetime(signup_date, '+' || (1 + (id * 7) % 5) || ' days', '+' || (3 + (id * 3) % 10) || ' hours')
      <= datetime('now');

-- Activity for the 21 days after each signup, thinning out as days pass so a
-- retention curve actually decays.
INSERT INTO events (event_id, user_id, event_name, ts, ingested_at)
WITH RECURSIVE day(d) AS (SELECT 0 UNION ALL SELECT d + 1 FROM day WHERE d < 20)
SELECT
  'evt_new_' || u.id || '_' || d,
  u.id,
  CASE (u.id + d) % 4
    WHEN 0 THEN 'view_dashboard'
    WHEN 1 THEN 'create_project'
    WHEN 2 THEN 'invite_teammate'
    ELSE 'checkout'
  END,
  datetime(u.signup_date, '+' || d || ' days', '+' || (2 + (u.id * 7 + d * 3) % 20) || ' hours'),
  datetime(u.signup_date, '+' || d || ' days', '+' || (2 + (u.id * 7 + d * 3) % 20) || ' hours', '+' || (4 + (u.id + d) % 50) || ' seconds')
FROM users u
JOIN day
WHERE (u.id * 3 + d * 7) % 5 < 3 - (d / 9)
  AND datetime(u.signup_date, '+' || d || ' days', '+' || (2 + (u.id * 7 + d * 3) % 20) || ' hours')
      <= datetime('now');

-- Activity over the last 30 days regardless of signup date, so "active users in
-- the last 28 days" isn't limited to the newest cohorts.
INSERT INTO events (event_id, user_id, event_name, ts, ingested_at)
WITH RECURSIVE day(d) AS (SELECT 0 UNION ALL SELECT d + 1 FROM day WHERE d < 29)
SELECT
  'evt_recent_' || u.id || '_' || d,
  u.id,
  CASE (u.id * 3 + d) % 3
    WHEN 0 THEN 'view_dashboard'
    WHEN 1 THEN 'checkout'
    ELSE 'create_project'
  END,
  datetime('now', '-' || d || ' days', '-' || ((u.id * 5 + d * 7) % 20) || ' hours'),
  datetime('now', '-' || d || ' days', '-' || ((u.id * 5 + d * 7) % 20) || ' hours', '+' || (5 + (u.id * 3 + d) % 45) || ' seconds')
FROM users u
JOIN day
WHERE (u.id * 7 + d * 5) % 6 < 2
  -- Every fifth user has gone quiet, so churn/active-user queries have signal.
  AND u.id % 5 <> 0
  AND u.signup_date <= date('now', '-' || d || ' days');

-- At-least-once delivery: ~5% of event rows arrive twice, same event_id, later
-- ingested_at. Snapshotted into a temp table first so the INSERT can't read its
-- own output.
CREATE TEMP TABLE _event_dupes AS
SELECT
  event_id,
  user_id,
  event_name,
  ts,
  datetime(ingested_at, '+' || (45 + rowid % 900) || ' seconds') AS ingested_at
FROM events WHERE rowid % 19 = 0;
INSERT INTO events (event_id, user_id, event_name, ts, ingested_at)
SELECT event_id, user_id, event_name, ts, ingested_at FROM _event_dupes;
DROP TABLE _event_dupes;

-- The +seconds on ingested_at can cross the current time for an event that
-- just happened. Clamp rather than drop the row: the event is real.
UPDATE events SET ingested_at = datetime('now') WHERE ingested_at > datetime('now');

CREATE INDEX events_user_ts ON events (user_id, ts);

CREATE TABLE sessions (
  user_id INTEGER NOT NULL,
  started_at TEXT NOT NULL,
  ended_at TEXT
);

INSERT INTO sessions (user_id, started_at, ended_at)
WITH RECURSIVE seq(n) AS (SELECT 1 UNION ALL SELECT n + 1 FROM seq WHERE n < 750)
SELECT
  1 + (n * 7) % 120,
  datetime('now', '-' || ((n * 5) % 30) || ' days', '-' || ((n * 13) % 24) || ' hours'),
  CASE WHEN n % 31 = 0 THEN NULL
       ELSE datetime(
         'now',
         '-' || ((n * 5) % 30) || ' days',
         '-' || ((n * 13) % 24) || ' hours',
         '+' || (3 + (n * 17) % 90) || ' minutes'
       )
  END
FROM seq;

-- Two devices at once: deliberate overlaps so "find overlapping sessions" has
-- answers to find.
CREATE TEMP TABLE _session_overlaps AS
SELECT user_id, datetime(started_at, '+10 minutes') AS started_at,
       datetime(started_at, '+55 minutes') AS ended_at
FROM sessions
WHERE rowid % 23 = 0 AND datetime(started_at, '+55 minutes') <= datetime('now');
INSERT INTO sessions (user_id, started_at, ended_at) SELECT * FROM _session_overlaps;
DROP TABLE _session_overlaps;

-- A session that would end in the future simply hasn't ended yet. This is where
-- most of the NULL ended_at rows come from, which is exactly how it works in a
-- real sessions table at 10am on a weekday.
UPDATE sessions SET ended_at = NULL WHERE ended_at > datetime('now');

CREATE TABLE plans (
  name TEXT PRIMARY KEY,
  monthly_price REAL NOT NULL
);
INSERT INTO plans (name, monthly_price)
VALUES ('free', 0), ('pro', 25), ('team', 80), ('enterprise', 400);

CREATE TABLE subscriptions (
  user_id INTEGER NOT NULL REFERENCES users(id),
  plan TEXT NOT NULL REFERENCES plans(name),
  started_at TEXT NOT NULL,
  ended_at TEXT
);

-- First subscription for everyone, starting at signup, plan consistent with the
-- account's segment. NULL ended_at = still paying. An end date that would land
-- in the future stays NULL — a subscription that hasn't happened yet would wreck
-- any month-over-month retention query.
INSERT INTO subscriptions (user_id, plan, started_at, ended_at)
SELECT
  id,
  CASE segment
    WHEN 'enterprise' THEN 'enterprise'
    WHEN 'mid_market' THEN 'team'
    ELSE CASE WHEN id % 3 = 0 THEN 'free' ELSE 'pro' END
  END,
  signup_date,
  CASE
    WHEN id % 3 = 0 AND date(signup_date, '+' || (30 + (id * 9) % 90) || ' days') <= date('now')
      THEN date(signup_date, '+' || (30 + (id * 9) % 90) || ' days')
    ELSE NULL
  END
FROM users;

-- The ones who ended a plan mostly came back on a different one — up for some,
-- down for others — which is what makes expansion and contraction visible in
-- net revenue retention. Every fifth user never came back at all.
CREATE TEMP TABLE _resubs AS
SELECT
  user_id,
  -- Both directions on purpose: NRR is only interesting when some accounts
  -- expand and others contract in the same month.
  CASE
    WHEN plan = 'team' AND user_id % 2 = 0 THEN 'enterprise'
    WHEN plan = 'team' THEN 'pro'
    WHEN plan = 'enterprise' THEN 'team'
    WHEN plan = 'pro' THEN 'team'
    ELSE 'pro'
  END AS plan,
  date(ended_at, '+1 day') AS started_at,
  CASE
    WHEN user_id % 9 = 0 AND date(ended_at, '+60 days') <= date('now')
      THEN date(ended_at, '+60 days')
    ELSE NULL
  END AS ended_at
FROM subscriptions
WHERE ended_at IS NOT NULL
  AND user_id % 5 <> 0
  AND date(ended_at, '+1 day') <= date('now');
INSERT INTO subscriptions (user_id, plan, started_at, ended_at)
SELECT user_id, plan, started_at, ended_at FROM _resubs;
DROP TABLE _resubs;
`;
